### ISSUE TITLE
投稿

### ISSUE THREAD

**Issue by Markli66** [zsio/Free-GPT-No-Auth#4]
我个人维护的ChatGPT公益站点，基于[Yidadaa](https://github.com/Yidadaa/ChatGPT-Next-Web)的一键拥有你自己的跨平台 ChatGPT 应用。来部署，并且承诺该站点后续绝对不会出现付费会话等操作。 地址是 https://ikunn.icu/   如果作者希望有些其他交流我们也可以共同探讨。

**Comment by zsio** [comment]
非常感谢您提供的网站
