### ISSUE TITLE
国内服务器部署如何添加代理

### ISSUE THREAD

**Issue by ODomWang** [zsio/Free-GPT-No-Auth#6]

**Comment by zsio** [comment]
无需代理，直接部署就行。第一个网站也就是FreeGPT，使用的是我自己的api接口，国内是可以直接访问的。

**Comment by zsio** [comment]
如果你想使用openai的接口在国内部署属于自己的gpt，可以在国外服务器反代接口就可以了。

**Comment by ODomWang** [comment]
是的 目前我部署在百度云 只有第一个可以使用 其他的都打不开 sumu1.com

**Comment by zsio** [comment]
是这样的，除了第一个我自建的FreeGPT，现在几乎没有人愿意免费公开、不加广告、无需登录的gpt了。

**Comment by ODomWang** [comment]
是的 我之前也是免费 顶不住每个月费用关闭了

**Comment by ODomWang** [comment]
老哥 大义。

**Comment by zsio** [comment]
嗐
